name: init-branch
on: create

jobs:
  model-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Parsing repo ref data
      shell: bash
      run: |
        REF=${{ inputs.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"

        REF_TYPE="${PATHS[1]}"
        echo $REF_TYPE
        echo "REF_TYPE=$(echo ${REF_TYPE})" >> $GITHUB_ENV
    - uses: Wimmics/olivaw/init-branch@test-0.0.6-2
      if: ${{ env.REF_TYPE != 'tags' }}
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}
