name: model-test
on: push

jobs:
  model-test:
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/model-test@v0.0.8
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}