name: model-test
on: push

jobs:
  model-test:
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/model-test@v0.0.1
      with:
        repository: ${{ github.server_url }}/${{ github.repository }}
        ref: ${{ github.ref }}
        