name: model-test
on: push

jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@baf62d0e79022dc200f24e7cfe445b2bc540f65f
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}