name: model-test
on: push





jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@1f74a58435d1ccd8a09329002ff1a3531b3a3397
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}