name: model-test
on: push

jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@29169fc5a81badfa6e2be4f40890fe9f47369862
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}