name: model-test
on: push

jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@7106a0f8b49335374367ee2fe5c6f63e438edda0
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}