name: model-test
on: push

jobs:
  model-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "MAIN=main" >> $GITHUB_ENV
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
    - uses: Wimmics/olivaw/test-actions@9529c6b54932a76c39939aefe8c23caa516ba5dd
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}
        data-test: true
        model-test: true
        query-test: true
        commit-report: ${{ env.BRANCH == env.MAIN }}
        archive-report: true


