name: model-test
on: push

jobs:
  model-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@f8d1440c00e41483244fc0545f3db73f03617934
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}
        data-test: true
        model-test: true
        query-test: true
        commit-report: true
        archive-report: true



