name: model-test
on: push

jobs:
  model-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@06a64207ac253f6e8a8aa6008e8ade746a36e63b
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}
        data-test: true
        model-test: true
        query-test: true
        commit-report: true
        archive-report: true


