name: model-test
on: push

jobs:
  model-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@6287fca0560f11c0ed24aecceaa61709d6c2353a
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        gist-secret: ${{ secrets.GIST_SECRET }}
        data-test: true
        model-test: true
        query-test: true
        commit-report: true
        archive-report: true


