name: model-test
on: push

jobs:
  olivaw-test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: Wimmics/olivaw/test-actions@test-0.0.6
      with:
        gist-secret: ${{ secrets.GIST_SECRET }}
